#file: noinspection SpellCheckingInspection
with-expecter: true
dir: "{{.InterfaceDir}}"
inpackage: true
packages:
  github.com/metamogul/timestone:
    interfaces:
      Action:
  github.com/metamogul/timestone/simulation/internal/events:
    interfaces:
      Generator: