#file: noinspection SpellCheckingInspection
with-expecter: true
dir: "{{.InterfaceDir}}"
inpackage: true
packages:
  github.com/metamogul/timestone/v2:
    interfaces:
      Action:
  github.com/metamogul/timestone/v2/simulation/internal/events:
    interfaces:
      Generator: